import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative w-full">
        <div className="flex justify-center fixed top-0 right-0 left-0 p-8 bg-black text-white">
          <div className="w-full flex justify-between items-center gap-20">
            <Link href="/" className="title">SITE</Link>
            <Link href="https://www.mercadolivre.com.br/" target="_blank">Mercado Livre</Link>
            <Link href="/notification">Notificações</Link>
            <Link href="/dispara-log">Disparar Log</Link>
          </div>
        </div>
        
        {children}
      </body>
    </html>
  );
}
